---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: gcpods-jx-test1
    namespace: jx-test1
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: gcpods-per-namespace
subjects:
    - kind: ServiceAccount
      name: jx-gcpods
      namespace: jx
