# without namespace, would be placed in {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: gcpods-default
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: gcpods-per-namespace
subjects:
    - kind: ServiceAccount
      name: jx-gcpods
      namespace: jx
