---
apiVersion: v1
kind: Service
metadata:
    name: cheese
    namespace: some-other-namespace
    labels:
        chart: cheese
    annotations:
        gitops.jenkins-x.io/namespaceChange: keep-namespace-move-file
spec:
    ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
          name: http
    selector:
        app: cheese
